#!/usr/bin/env python
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path


def _render_markdown(payload: dict) -> str:
    ts = str(payload.get("ts", ""))
    title = str(payload.get("title", "AI Team Sync"))
    source = str(payload.get("source", "aiteam"))
    notebook_id = str(payload.get("notebook_id", ""))
    content = str(payload.get("content", "")).strip()

    lines = [
        f"# {title}",
        "",
        f"- Exported at: {ts or datetime.now(timezone.utc).isoformat()}",
        f"- Source: {source}",
        f"- Notebook ID: {notebook_id or '-'}",
        "",
        "---",
        "",
        content or "(empty payload)",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="NotebookLM local ingest bridge")
    parser.add_argument("--payload-path", required=True, help="Path to payload JSON generated by notebooklm-sync")
    parser.add_argument("--runtime-dir", default="runtime", help="Runtime directory")
    args = parser.parse_args()

    payload_path = Path(args.payload_path)
    runtime_dir = Path(args.runtime_dir)

    if not payload_path.exists():
        print(f"payload_not_found: {payload_path}")
        return 1

    try:
        payload = json.loads(payload_path.read_text(encoding="utf-8"))
    except Exception as exc:
        print(f"payload_invalid_json: {exc}")
        return 1

    ready_dir = runtime_dir / "notebooklm_ready"
    ready_dir.mkdir(parents=True, exist_ok=True)

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    ready_path = ready_dir / f"notebooklm_ready_{stamp}.md"
    ready_path.write_text(_render_markdown(payload), encoding="utf-8")

    status = {
        "ts": datetime.now(timezone.utc).isoformat(),
        "mode": "command",
        "success": True,
        "details": f"Prepared markdown for NotebookLM upload: {ready_path}",
        "ready_path": str(ready_path),
        "payload_path": str(payload_path),
    }
    (runtime_dir / "notebooklm_bridge_status.json").write_text(
        json.dumps(status, indent=2, ensure_ascii=True),
        encoding="utf-8",
    )

    print(f"ready_path={ready_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
